name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]  # change to 'master' if that's your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        personal_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        external_repository: alex-allier9/alex-allier9.github.io
        publish_dir: ./
        publish_branch: main