name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout preu-jmc
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Deploy to alex-allier9.github.io
      uses: peaceiris/actions-gh-pages@v3
      with:
        personal_token: ${{ secrets.GITHUB_PAGES_TOKEN }}
        external_repository: alex-allier9/alex-allier9.github.io
        publish_branch: main
        publish_dir: ./
        commit_message: 'Deploy from preu-jmc: ${{ github.sha }}'
        
        # Configuraciones específicas
        allow_empty_commit: false
        keep_files: false
        force_orphan: false
        
        # Excluir archivos que no queremos copiar
        exclude_assets: |
          .gitignore
          .github/
          README.md
          markdown files/
          *.md