name: Deploy to Cloudflare Pages

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy to Cloudflare Pages
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Deploy to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: preujmc
          directory: .
          # Build command is not needed for static sites
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          
  # Job adicional para validar HTML
  validate:
    runs-on: ubuntu-latest
    name: Validate HTML/CSS
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      - name: Install HTML Validator
        run: |
          npm install -g html-validate
          npm install -g stylelint stylelint-config-standard
          
      - name: Validate HTML files
        run: |
          html-validate *.html
          
      - name: Validate CSS files
        run: |
          stylelint "css/**/*.css"
